spring:
  datasource:
    url: jdbc:mysql://localhost:3306/find-your-house?createDatabaseIfNotExist=true
    username: 'root'
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: localhost
    port: 25
    username: iheb
    password: iheb
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:lPkiw2n6vOouaX6o+R6WkRMmiWR6/Fa/enzroJqY78YS/FSjEf8Er1iUaUy0RNan} # Consider using env variables for security
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 9090
